orbs:
  node: circleci/node@1.1
version: 2.1
jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
      - run: yarn lint
      - run: yarn test
      - run: yarn build
