orbs:
  node: circleci/node@1.1
version: 2.1
jobs:
  build:
    executor:
      name: node/default
      tag: '12.13'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
      - run:
          name: Run Linter
          command: yarn lint
      - run:
          name: Run Tests
          command: yarn test
      - run:
          name: Run Build
          command: yarn build
