export const ADD_GRAPH = 'ADD_GRAPH';
export type ADD_GRAPH = 'ADD_GRAPH';
export const ADD_NODE = 'ADD_NODE';
export type ADD_NODE = 'ADD_NODE';
export const NEW_GRAPH_LAYOUT = 'NEW_GRAPH_LAYOUT';
export type NEW_GRAPH_LAYOUT = 'NEW_GRAPH_LAYOUT';
export const TOGGLE_FREEZE_LAYOUT = 'TOGGLE_FREEZE_LAYOUT';
export type TOGGLE_FREEZE_LAYOUT = 'TOGGLE_FREEZE_LAYOUT';
