export const graph = {
  nodes: [
    { id: 0 },
    { id: 1 },
    { id: 2 },
    { id: 3 },
    { id: 4 },
    { id: 5 },
    { id: 6 },
    { id: 7 },
    { id: 8 },
    { id: 9 },
  ],
  links: [
    { source: 1, target: 2 },
    { source: 1, target: 4 },
    { source: 1, target: 8 },
    { source: 2, target: 4 },
    { source: 2, target: 9 },
    { source: 3, target: 6 },
    { source: 3, target: 8 },
    { source: 4, target: 5 },
    { source: 5, target: 8 },
    { source: 7, target: 8 },
  ],
};
